language: "node_js"
node_js: "8"

before_script:
  - npm run build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: kevin-k/resume-react
  target_branch: gh-pages
  on:
    branch: master #
